name: Deploy to ec2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST_DNS }} 
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/
            if [ -d eduardoos ]; then
              cd eduardoos
              sudo git pull 
            else
              sudo git clone https://github.com/EduardoOsteicoechea/eduardoos.git
              cd eduardoos
            fi
            if [ -d api ]; then
              cd api
              sudo dotnet restore
              sudo dotnet build -c Release
              sudo dotnet publish -c Release -o /var/www/html/eduardoos/api/publish
              cd /var/www/html/eduardoos/api/publish
              sudo kill -9 $(pgrep -f "eduardoosapi.dll") || true #ignore if no process found.
              nohup sudo dotnet eduardoosapi.dll &
            fi
            sudo nginx -s reload

      - name: Check API status
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            curl -f http://<your_api_endpoint>/health # Replace with your API's health check endpoint